# Generated by Django 3.2.10 on 2022-06-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='Userinfo',
        ),
    ]
