# Generated by Django 3.2.10 on 2022-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_userform_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
