# Generated by Django 3.2.13 on 2022-06-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userinfo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
