# Generated by Django 3.2.13 on 2022-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userinfo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='datacaptb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('imgcount', models.IntegerField()),
                ('clink', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
