# Generated by Django 3.2.13 on 2022-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userinfo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='captureDatasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=1000)),
                ('images_count', models.IntegerField()),
            ],
        ),
    ]
